services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - node.name=single_node
      - cluster.name=NETOLOGY_HW_single_node
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./DB-11-03HW/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: kibana:8.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:8.17.0
    environment:
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./logstash/config.yml:/usr/share/logstash/config/logstash.yml
      - ./DB-11-03HW/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./DB-11-03HW/logstash/pipelines:/usr/share/logstash/pipeline/
      - ./DB-11-03HW/nginx-logs:/var/log/nginx
    depends_on:
      - elasticsearch
      - web

  web:
    image: nginx
    volumes:
      - ./DB-11-03HW/nginx-logs:/var/log/nginx
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80

volumes:
  elasticsearch-data:
    driver: local
